### ISSUE TITLE
How to use into another addon

### ISSUE THREAD

**Issue by rmpestano** [gastaldi/twitter-addon#1]
I want to use this addon inside another addon, which maven coordinates should I declare? 

Also I'd like it to be optional so when user is installing my addon it doesn't need to have twitter addon, is it possible?

Thanks in advance!

**Comment by gastaldi** [comment]
Hi @rmpestano,

The addon needs to be in a Maven repository. Since it is not published anywhere, you can use jitpack.io for that: https://jitpack.io/#gastaldi/twitter-addon/master-SNAPSHOT

Add this dependency to your addon and add the `<optional>true</optional>` tag in the dependency to make it optional. If you have any class that requires the Twitter addon classes and Forge doesn't find it, it will remove from deployment.

**Comment by rmpestano** [comment]
Hi @gastaldi, thanks for the tip but I could not download from jitpack, I think its a proxy thing so I'll try at home:

```
Downloading: https://jitpack.io/com/github/gastald/twitter-addon/master-SNAPSHOT/twitter-addon-master-SNAPSHOT.pom

Could not transfer artifact com.github.gastald:twitter-addon:pom:master-SNAPSHOT from/to jitpack.io (https://jitpack.io): Not authorized , ReasonPhrase:Unauthorized
```

**Comment by rmpestano** [comment]
Hi @gastaldi ,

still no luck, there is anything else I need to configure in maven to use jitpack? here's what I have:

```
<dependency>
			<groupId>com.github.gastald</groupId>
			<artifactId>twitter-addon</artifactId>
			<version>master-SNAPSHOT</version>
			<optional>true</optional>
		</dependency>
```

and repository:

```
<repositories>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
	</repositories>
```

and the  error:

```
[ERROR] Failed to execute goal on project music-addon: Could not resolve dependencies for project com.github.forge.addon:music-addon:jar:1.0.4-SNAPSHOT: Failed to collect dependencies at com.github.gastald:twitter-addon:jar:master-SNAPSHOT: Failed to read artifact descriptor for com.github.gastald:twitter-addon:jar:master-SNAPSHOT: Could not transfer artifact com.github.gastald:twitter-addon:pom:master-SNAPSHOT from/to jitpack.io (https://jitpack.io): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]

```

**Comment by gastaldi** [comment]
The groupId is wrong, it should read com.github.gastaldi

Em 29 de jul de 2017 14:19, "Rafael M. Pestano" <notifications@github.com>
escreveu:

Hi @gastaldi <https://github.com/gastaldi> ,

still no luck, there is anything else I need to configure in maven to use
jitpack? here's what I have:

<dependency>
			<groupId>com.github.gastald</groupId>
			<artifactId>twitter-addon</artifactId>
			<version>master-SNAPSHOT</version>
			<optional>true</optional>
		</dependency>

and repository:

<repositories>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
	</repositories>

and the error:

[ERROR] Failed to execute goal on project music-addon: Could not
resolve dependencies for project
com.github.forge.addon:music-addon:jar:1.0.4-SNAPSHOT: Failed to
collect dependencies at
com.github.gastald:twitter-addon:jar:master-SNAPSHOT: Failed to read
artifact descriptor for
com.github.gastald:twitter-addon:jar:master-SNAPSHOT: Could not
transfer artifact com.github.gastald:twitter-addon:pom:master-SNAPSHOT
from/to jitpack.io (https://jitpack.io): Not authorized ,
ReasonPhrase:Unauthorized. -> [Help 1]


—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/gastaldi/twitter-addon/issues/1#issuecomment-318845363>,
or mute the thread

**Comment by rmpestano** [comment]
Yes, my bad, thank you again @gastaldi :+1:
